### ISSUE TITLE
run depthai_blazepose/demo.py -e -xyz has open3d error

### ISSUE THREAD

**Issue by stephanschulz** [geaxgx/depthai_pipeline_graph#3]
If i understand the readme correctly i need to point the graph app to where my starter script is located.
So, i added the file path with the usual arguments the depthai_blazepose example.

But i get an error about `open3d` not being present.
The demo.py works when run directly from within the main folder.

```stephanschulz@Komputer depthai_pipeline_graph % pipeline_graph run "/Users/stephanschulz/Documents/depthai-python-2/depthai_blazepose/demo.py -e -xyz"
Program exited.
Traceback (most recent call last):
  File "/Users/stephanschulz/Documents/depthai-python-2/depthai_blazepose/demo.py", line 3, in <module>
    from BlazeposeRenderer import BlazeposeRenderer
  File "/Users/stephanschulz/Documents/depthai-python-2/depthai_blazepose/BlazeposeRenderer.py", line 3, in <module>
    from o3d_utils import Visu3D
  File "/Users/stephanschulz/Documents/depthai-python-2/depthai_blazepose/o3d_utils.py", line 1, in <module>
    import open3d as o3d
ModuleNotFoundError: No module named 'open3d'


Something went wrong, the schema could not be extracted```

**Comment by stephanschulz** [comment]
ah i forgot to include the python command.

```
pipeline_graph run "python3.8 /Users/stephanschulz/Documents/depthai-python-2/depthai_blazepose/demo.py -e -xyz"
```
works now
