### ISSUE TITLE
Not able to ingest output from C++ output to console pasted into .txt

### ISSUE THREAD

**Issue by adammpolak** [geaxgx/depthai_pipeline_graph#7]
I copied the output from console on my C++ project when setting `DEPTHAI_LEVEL` to `debug`.

The file is here: 
[pipeline.txt](https://github.com/geaxgx/depthai_pipeline_graph/files/11463879/pipeline.txt)

When trying to run: `pipeline_graph from_file ./pipeline.txt`

I get this error:
```
pipeline_graph from_file ./pipeline.txt
Pipeline schema retrieved
Traceback (most recent call last):
  File "/home/adam/.local/bin/pipeline_graph", line 8, in <module>
    sys.exit(main())
  File "/home/adam/.local/lib/python3.8/site-packages/depthai_pipeline_graph/pipeline_graph.py", line 375, in main
    p.cmd_tool(args)
  File "/home/adam/.local/lib/python3.8/site-packages/depthai_pipeline_graph/pipeline_graph.py", line 218, in cmd_tool
    if args.verbose:
AttributeError: 'Namespace' object has no attribute 'verbose'
```

**Comment by adammpolak** [comment]
From pipeline.txt file above:

```
[2023-05-11 19:54:36.756] [debug] Starting to open
detection path is ../../models/person-detection-retail-0013-4-shave.blob
reid path is ../../models/person-reidentification-retail-0288-4-shave.blob
[2023-05-11 19:54:36.760] [debug] Library information - version: 2.21.2, commit: 125feb8c2e16ee4bf71b7873a7b990f1c5f17b18 from 2023-04-05 21:24:25 +0300, build: 2023-04-27 22:50:11 +0000
[2023-05-11 19:54:36.761] [debug] Initialize - finished
Creating Person Detection Neural Network...
[2023-05-11 19:54:36.840] [debug] Resources - Archive 'depthai-bootloader-fwp-0.0.24.tar.xz' open: 6ms, archive read: 72ms
Creating Recognition Neural Network...
Trying to create pipeline
[2023-05-11 19:54:36.957] [debug] Found an actual device by given DeviceInfo: DeviceInfo(name=192.168.10.43, mxid=18443010C16C0F0900, X_LINK_BOOTLOADER, X_LINK_TCP_IP, X_LINK_MYRIAD_X, X_LINK_SUCCESS)
[2023-05-11 19:54:36.957] [debug] Device - OpenVINO version: 2022.1
[2023-05-11 19:54:36.958] [debug] Device - BoardConfig: {"camera":[],"emmc":null,"gpio":[],"imu":null,"logDevicePrints":null,"logPath":null,"logSizeMax":null,"logVerbosity":null,"network":{"mtu":0,"xlinkTcpNoDelay":true},"nonExclusiveMode":false,"pcieInternalClock":null,"sysctl":[],"uart":[],"usb":{"flashBootedPid":63037,"flashBootedVid":999,"maxSpeed":3,"pid":63035,"vid":999},"usb3PhyInternalClock":null,"watchdogInitialDelayMs":null,"watchdogTimeoutMs":null} 
libnop:
0000: b9 11 b9 05 81 e7 03 81 3b f6 81 e7 03 81 3d f6 03 b9 02 00 01 ba 00 be be bb 00 bb 00 be be be
0020: be be be be 00 bb 00 be
[2023-05-11 19:54:37.169] [debug] Resources - Archive 'depthai-device-fwp-3575b77f20e796b4e79953bf3d2ba22f0416ee8b.tar.xz' open: 2ms, archive read: 405ms
[2023-05-11 19:54:37.193] [debug] Searching for booted device: DeviceInfo(name=192.168.10.43, mxid=18443010C16C0F0900, X_LINK_BOOTLOADER, X_LINK_TCP_IP, X_LINK_MYRIAD_X, X_LINK_SUCCESS), name used as hint only
[2023-05-11 19:54:37.331] [debug] Connected bootloader version 0.0.15
[2023-05-11 19:54:37.331] [info] New bootloader version available. Device has: 0.0.15, available: 0.0.24
[2023-05-11 19:54:44.833] [warning] Monitor thread (device: 18443010C16C0F0900 [192.168.10.43]) - ping was missed, closing the device connection
[2023-05-11 19:54:46.833] [debug] XLinkResetRemoteTimeout returned: X_LINK_TIMEOUT
[2023-05-11 19:54:46.833] [debug] XLinkResetRemote of linkId: (0)
[2023-05-11 19:54:46.833] [debug] Booting FW with Bootloader. Version 0.0.15, Time taken: 9501ms
[2023-05-11 19:54:46.834] [debug] DeviceBootloader about to be closed...
[2023-05-11 19:54:48.084] [debug] DeviceBootloader closed, 1250
[2023-05-11 19:54:48.090] [debug] Searching for booted device: DeviceInfo(name=192.168.10.43, mxid=18443010C16C0F0900, X_LINK_BOOTED, X_LINK_TCP_IP, X_LINK_MYRIAD_X, X_LINK_SUCCESS), name used as hint only
[18443010C16C0F0900] [192.168.10.43] [9.774] [system] [info] Memory Usage - DDR: 0.12 / 340.34 MiB, CMX: 2.04 / 2.50 MiB, LeonOS Heap: 25.29 / 77.23 MiB, LeonRT Heap: 2.89 / 41.14 MiB
[18443010C16C0F0900] [192.168.10.43] [9.774] [system] [info] Temperatures - Average: 41.43C, CSS: 42.35C, MSS 40.97C, UPA: 40.97C, DSS: 41.43C
[18443010C16C0F0900] [192.168.10.43] [9.774] [system] [info] Cpu Usage - LeonOS 28.42%, LeonRT: 0.30%
[2023-05-11 19:54:48.121] [debug] Schema dump: {"connections":[{"node1Id":7,"node1Output":"out","node1OutputGroup":"","node2Id":8,"node2Input":"in","node2InputGroup":""},{"node1Id":6,"node1Output":"out","node1OutputGroup":"","node2Id":7,"node2Input":"in","node2InputGroup":""},{"node1Id":5,"node1Output":"manip_img","node1OutputGroup":"io","node2Id":6,"node2Input":"inputImage","node2InputGroup":""},{"node1Id":5,"node1Output":"manip_cfg","node1OutputGroup":"io","node2Id":6,"node2Input":"inputConfig","node2InputGroup":""},{"node1Id":3,"node1Output":"passthrough","node1OutputGroup":"","node2Id":5,"node2Input":"passthrough","node2InputGroup":"io"},{"node1Id":3,"node1Output":"out","node1OutputGroup":"","node2Id":5,"node2Input":"dets_in","node2InputGroup":"io"},{"node1Id":0,"node1Output":"preview","node1OutputGroup":"","node2Id":5,"node2Input":"preview","node2InputGroup":"io"},{"node1Id":3,"node1Output":"out","node1OutputGroup":"","node2Id":4,"node2Input":"in","node2InputGroup":""},{"node1Id":2,"node1Output":"out","node1OutputGroup":"","node2Id":3,"node2Input":"in","node2InputGroup":""},{"node1Id":0,"node1Output":"preview","node1OutputGroup":"","node2Id":2,"node2Input":"inputImage","node2InputGroup":""},{"node1Id":0,"node1Output":"preview","node1OutputGroup":"","node2Id":1,"node2Input":"in","node2InputGroup":""}],"globalProperties":{"calibData":null,"cameraTuningBlobSize":null,"cameraTuningBlobUri":"","leonCssFrequencyHz":700000000.0,"leonMssFrequencyHz":700000000.0,"pipelineName":null,"pipelineVersion":null,"sippBufferSize":18432,"sippDmaBufferSize":16384,"xlinkChunkSize":-1},"nodes":[[0,{"id":0,"ioInfo":[[["","video"],{"blocking":false,"group":"","id":28,"name":"video","queueSize":8,"type":0,"waitForMessage":false}],[["","still"],{"blocking":false,"group":"","id":26,"name":"still","queueSize":8,"type":0,"waitForMessage":false}],[["","isp"],{"blocking":false,"group":"","id":25,"name":"isp","queueSize":8,"type":0,"waitForMessage":false}],[["","preview"],{"blocking":false,"group":"","id":27,"name":"preview","queueSize":8,"type":0,"waitForMessage":false}],[["","raw"],{"blocking":false,"group":"","id":24,"name":"raw","queueSize":8,"type":0,"waitForMessage":false}],[["","frameEvent"],{"blocking":false,"group":"","id":23,"name":"frameEvent","queueSize":8,"type":0,"waitForMessage":false}],[["","inputConfig"],{"blocking":false,"group":"","id":22,"name":"inputConfig","queueSize":8,"type":3,"waitForMessage":false}],[["","inputControl"],{"blocking":true,"group":"","id":21,"name":"inputControl","queueSize":8,"type":3,"waitForMessage":false}]],"name":"ColorCamera","properties":[185,25,185,27,0,3,0,0,0,185,3,0,0,0,185,5,0,0,0,0,0,185,5,0,0,0,0,0,0,0,0,0,0,0,0,185,3,0,0,0,185,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,189,0,255,1,0,0,129,192,3,129,96,6,255,255,255,255,0,136,0,0,160,64,0,136,0,0,128,191,136,0,0,128,191,1,185,4,0,0,0,0,3,3,4,10,4]}],[1,{"id":1,"ioInfo":[[["","in"],{"blocking":true,"group":"","id":20,"name":"in","queueSize":8,"type":3,"waitForMessage":true}]],"name":"XLinkOut","properties":[185,3,136,0,0,128,191,189,3,114,103,98,0]}],[2,{"id":2,"ioInfo":[[["","out"],{"blocking":false,"group":"","id":19,"name":"out","queueSize":8,"type":0,"waitForMessage":false}],[["","inputConfig"],{"blocking":true,"group":"","id":18,"name":"inputConfig","queueSize":8,"type":3,"waitForMessage":false}],[["","inputImage"],{"blocking":true,"group":"","id":17,"name":"inputImage","queueSize":8,"type":3,"waitForMessage":true}]],"name":"ImageManip","properties":[185,6,185,8,185,7,185,4,136,0,0,0,0,136,0,0,0,0,136,0,0,0,0,136,0,0,0,0,185,3,185,2,136,0,0,0,0,136,0,0,0,0,185,2,136,0,0,0,0,136,0,0,0,0,136,0,0,0,0,0,136,0,0,128,63,136,0,0,128,63,0,1,185,15,133,32,2,133,64,1,0,0,0,0,186,0,1,0,186,0,0,0,136,0,0,0,0,0,1,185,6,7,0,0,0,0,133,255,0,0,1,1,0,0,134,0,0,16,0,4,0,0,189,0]}],[3,{"id":3,"ioInfo":[[["","out"],{"blocking":false,"group":"","id":16,"name":"out","queueSize":8,"type":0,"waitForMessage":false}],[["","passthrough"],{"blocking":false,"group":"","id":15,"name":"passthrough","queueSize":8,"type":0,"waitForMessage":false}],[["","in"],{"blocking":true,"group":"","id":14,"name":"in","queueSize":5,"type":3,"waitForMessage":true}]],"name":"DetectionNetwork","properties":[185,6,130,75,30,35,0,189,12,97,115,115,101,116,58,95,95,98,108,111,98,8,0,0,185,7,1,136,0,0,0,63,0,0,186,0,187,0,136,0,0,0,0]}],[4,{"id":4,"ioInfo":[[["","in"],{"blocking":true,"group":"","id":13,"name":"in","queueSize":8,"type":3,"waitForMessage":true}]],"name":"XLinkOut","properties":[185,3,136,0,0,128,191,189,9,100,101,116,101,99,116,105,111,110,0]}],[5,{"id":5,"ioInfo":[[["io","manip_cfg"],{"blocking":false,"group":"io","id":12,"name":"manip_cfg","queueSize":8,"type":0,"waitForMessage":false}],[["io","manip_img"],{"blocking":false,"group":"io","id":11,"name":"manip_img","queueSize":8,"type":0,"waitForMessage":false}],[["io","preview"],{"blocking":true,"group":"io","id":10,"name":"preview","queueSize":8,"type":3,"waitForMessage":false}],[["io","dets_in"],{"blocking":true,"group":"io","id":9,"name":"dets_in","queueSize":8,"type":3,"waitForMessage":false}],[["io","passthrough"],{"blocking":true,"group":"io","id":8,"name":"passthrough","queueSize":8,"type":3,"waitForMessage":false}]],"name":"Script","properties":[185,3,189,14,97,115,115,101,116,58,95,95,115,99,114,105,112,116,189,8,60,115,99,114,105,112,116,62,1]}],[6,{"id":6,"ioInfo":[[["","out"],{"blocking":false,"group":"","id":7,"name":"out","queueSize":8,"type":0,"waitForMessage":false}],[["","inputConfig"],{"blocking":true,"group":"","id":6,"name":"inputConfig","queueSize":8,"type":3,"waitForMessage":true}],[["","inputImage"],{"blocking":true,"group":"","id":5,"name":"inputImage","queueSize":8,"type":3,"waitForMessage":true}]],"name":"ImageManip","properties":[185,6,185,8,185,7,185,4,136,0,0,0,0,136,0,0,0,0,136,0,0,0,0,136,0,0,0,0,185,3,185,2,136,0,0,0,0,136,0,0,0,0,185,2,136,0,0,0,0,136,0,0,0,0,136,0,0,0,0,0,136,0,0,128,63,136,0,0,128,63,0,1,185,15,133,128,0,133,0,1,0,0,0,0,186,0,1,0,186,0,0,0,136,0,0,0,0,0,1,185,6,32,0,0,0,0,133,255,0,0,1,0,0,0,134,0,0,16,0,4,0,0,189,0]}],[7,{"id":7,"ioInfo":[[["","out"],{"blocking":false,"group":"","id":4,"name":"out","queueSize":8,"type":0,"waitForMessage":false}],[["","passthrough"],{"blocking":false,"group":"","id":3,"name":"passthrough","queueSize":8,"type":0,"waitForMessage":false}],[["","in"],{"blocking":true,"group":"","id":2,"name":"in","queueSize":5,"type":3,"waitForMessage":true}]],"name":"NeuralNetwork","properties":[185,5,130,126,177,13,0,189,12,97,115,115,101,116,58,95,95,98,108,111,98,8,0,0]}],[8,{"id":8,"ioInfo":[[["","in"],{"blocking":true,"group":"","id":1,"name":"in","queueSize":8,"type":3,"waitForMessage":true}]],"name":"XLinkOut","properties":[185,3,136,0,0,128,191,189,11,114,101,99,111,103,110,105,116,105,111,110,0]}]]}
[2023-05-11 19:54:48.121] [debug] Asset map dump: {"map":{"/node/3/__blob":{"alignment":64,"offset":900096,"size":2301515},"/node/5/__script":{"alignment":64,"offset":897408,"size":2644},"/node/7/__blob":{"alignment":64,"offset":0,"size":897406}}}
[18443010C16C0F0900] [192.168.10.43] [9.999] [system] [info] SIPP (Signal Image Processing Pipeline) internal buffer size '18432'B, DMA buffer size: '16384'B
[18443010C16C0F0900] [192.168.10.43] [10.035] [system] [info] ImageManip internal buffer size '393408'B, shave buffer size '35840'B
[18443010C16C0F0900] [192.168.10.43] [10.035] [system] [info] NeuralNetwork allocated resources: shaves: [0-12] cmx slices: [0-12] 
ColorCamera allocated resources: no shaves; cmx slices: [13-15] 
ImageManip allocated resources: shaves: [15-15] no cmx slices. 

[18443010C16C0F0900] [192.168.10.43] [10.050] [DetectionNetwork(3)] [info] Needed resources: shaves: 4, ddr: 10792960 
[18443010C16C0F0900] [192.168.10.43] [10.050] [DetectionNetwork(3)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[18443010C16C0F0900] [192.168.10.43] [10.052] [NeuralNetwork(7)] [info] Needed resources: shaves: 4, ddr: 786432 
[18443010C16C0F0900] [192.168.10.43] [10.052] [NeuralNetwork(7)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[18443010C16C0F0900] [192.168.10.43] [10.296] [DetectionNetwork(3)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Created pipeline
Connected cameras: 
/home/adam/dev/Sensor-Stream-Pipe/readers/oakd_xlink_full_reader.cc:400
0 RGB/CENTER/CAM_A 1 LEFT/CAM_B 2 RIGHT/CAM_C 
[2023-05-11 19:54:48.688] [debug] Done opening
/home/adam/dev/Sensor-Stream-Pipe/servers/ssp_server.cc:221
[18443010C16C0F0900] [192.168.10.43] [10.297] [DetectionNetwork(3)] [info] Inference thread count: 2, number of shaves allocated per thread: 4, number of Neural Compute Engines (NCE) allocated per thread: 1
/home/adam/dev/Sensor-Stream-Pipe/servers/ssp_server.cc:223
/home/adam/dev/Sensor-Stream-Pipe/servers/ssp_server.cc:235
[18443010C16C0F0900] [192.168.10.43] [10.297] [NeuralNetwork(7)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
[18443010C16C0F0900] [192.168.10.43] [10.297] [NeuralNetwork(7)] [info] Inference thread count: 2, number of shaves allocated per thread: 4, number of Neural Compute Engines (NCE) allocated per thread: 1
```

**Comment by geaxgx** [comment]
Hi,
I can run the same command on my computer with your file `pipeline.txt` without any problem:
![image](https://github.com/geaxgx/depthai_pipeline_graph/assets/28948232/539d6ee8-c103-4d47-b150-ba8b9994341d)

Can you try to uninstall and reinstall pipeline_graph to be sure you are using the last version:
```
pip3 uninstall depthai-pipeline-graph
pip3 install git+https://github.com/geaxgx/depthai_pipeline_graph.git
```
and check again ?

**Comment by adammpolak** [comment]
What is the command you used? Is it not `pipeline_graph from_file ./pipeline.txt`

**Comment by geaxgx** [comment]
Yes, I used this same command.

Actually, I don't understand in your error trace: 
```
File "/home/adam/.local/lib/python3.8/site-packages/depthai_pipeline_graph/pipeline_graph.py", line 375, in main
    p.cmd_tool(args)
```
where `p.cmd_tool(args)` is coming from ?

Can you send me the `/home/adam/.local/lib/python3.8/site-packages/depthai_pipeline_graph/pipeline_graph.py ` file?

**Comment by adammpolak** [comment]
[pipeline_graph.txt](https://github.com/geaxgx/depthai_pipeline_graph/files/11470038/pipeline_graph.txt)
attached

**Comment by geaxgx** [comment]
I understand what is happening. Your pipeline_graph.py is not from my repo but from this repo: https://github.com/luxonis/depthai_pipeline_graph (which is a fork from my repo). A few months ago, Luxonis told me that they wanted to include the pipeline_graph tool in their distrib,  I thought it was a part of the depthai_sdk but as I wasn't able to find it there, I was not sure whether the integration was effective or not, especially as their official documentation (https://docs.luxonis.com/en/latest/pages/support/#requesting-support) is still referencing my repo.

At the end, you should use the luxonis github repo as luxonis "has updated some features and added FPS counting"(!).
I consider that the Luxonis version is now the official version.
So if you have followed my initial recommendation of installing my version, you should first uninstall it and then install the luxonis version. 
And if you still get an error, you could open an issue on their github.

I will update my README to reference the Luxonis github, so that this problem does not occur again.

**Comment by adammpolak** [comment]
You rock thank you.
